### ISSUE TITLE
[BUG] Suddenly stopped working at 'converting'

### ISSUE THREAD

**Issue by StevenBeyen** [casualsnek/onthespot#147]
I've used Onthespot to download my playlists on Ubuntu.

It worked fine for about 1k songs, and then suddenly stopped working at the conversion from ogg to mp3, after download.

I've tried with different songs, it happens every single time.
I've tried running the ffmpeg command manually and it works, so the problem lies with Onthespot.

I suspect some overflow in the logs or something like this, can you tell me where the data files are stored?

**Comment by justin025** [comment]
Logs are in ~/.cache but the problem lies in your ffmpeg binary, not sure what build flags ubuntu uses but there are some official builds [here](https://johnvansickle.com/ffmpeg/). If you are very knowledgeable ffmpeg needs sdl and mp3 enabled at build time otherwise it gets stuck at converting. 

You could also try the onthespot_ffm builds which bundle a working version of ffmpeg:
https://github.com/casualsnek/onthespot/releases/tag/v0.5
https://file.io/1kyUxARvo2GC (personal build)

**Comment by StevenBeyen** [comment]
Thanks, I'll try this.

Then I don't understand why it worked fine for over a thousand songs, manually running ffmpeg still works, but using onthespot suddenly doesn't anymore.

**Comment by StevenBeyen** [comment]
I purged ffmpeg a couple of times and everything seems to work fine again. :smile:
